/*
 * This file is generated by jOOQ.
 */
package model;


import model.tables.Courses;
import model.tables.Subscriptions;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>skillbox</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SUBSCRIPTIONS_COURSE_IDX = Indexes0.SUBSCRIPTIONS_COURSE_IDX;
    public static final Index COURSES_TEACHER_IDX = Indexes0.COURSES_TEACHER_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SUBSCRIPTIONS_COURSE_IDX = Internal.createIndex("course_idx", Subscriptions.SUBSCRIPTIONS, new OrderField[] { Subscriptions.SUBSCRIPTIONS.COURSE_ID }, false);
        public static Index COURSES_TEACHER_IDX = Internal.createIndex("teacher_idx", Courses.COURSES, new OrderField[] { Courses.COURSES.TEACHER_ID }, false);
    }
}
