/*
 * This file is generated by jOOQ.
 */
package model;


import java.util.Arrays;
import java.util.List;

import model.tables.Courses;
import model.tables.Purchaselist;
import model.tables.PurchaselistBk;
import model.tables.Students;
import model.tables.Subscriptions;
import model.tables.Teachers;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Skillbox extends SchemaImpl {

    private static final long serialVersionUID = -1673432379;

    /**
     * The reference instance of <code>skillbox</code>
     */
    public static final Skillbox SKILLBOX = new Skillbox();

    /**
     * The table <code>skillbox.courses</code>.
     */
    public final Courses COURSES = Courses.COURSES;

    /**
     * The table <code>skillbox.purchaselist</code>.
     */
    public final Purchaselist PURCHASELIST = Purchaselist.PURCHASELIST;

    /**
     * The table <code>skillbox.purchaselist_bk</code>.
     */
    public final PurchaselistBk PURCHASELIST_BK = PurchaselistBk.PURCHASELIST_BK;

    /**
     * The table <code>skillbox.students</code>.
     */
    public final Students STUDENTS = Students.STUDENTS;

    /**
     * The table <code>skillbox.subscriptions</code>.
     */
    public final Subscriptions SUBSCRIPTIONS = Subscriptions.SUBSCRIPTIONS;

    /**
     * The table <code>skillbox.teachers</code>.
     */
    public final Teachers TEACHERS = Teachers.TEACHERS;

    /**
     * No further instances allowed
     */
    private Skillbox() {
        super("skillbox", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Courses.COURSES,
            Purchaselist.PURCHASELIST,
            PurchaselistBk.PURCHASELIST_BK,
            Students.STUDENTS,
            Subscriptions.SUBSCRIPTIONS,
            Teachers.TEACHERS);
    }
}
