/*
 * This file is generated by jOOQ.
 */
package model;


import model.tables.Courses;
import model.tables.Purchaselist;
import model.tables.PurchaselistBk;
import model.tables.Students;
import model.tables.Subscriptions;
import model.tables.Teachers;


/**
 * Convenience access to all tables in skillbox
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>skillbox.courses</code>.
     */
    public static final Courses COURSES = Courses.COURSES;

    /**
     * The table <code>skillbox.purchaselist</code>.
     */
    public static final Purchaselist PURCHASELIST = Purchaselist.PURCHASELIST;

    /**
     * The table <code>skillbox.purchaselist_bk</code>.
     */
    public static final PurchaselistBk PURCHASELIST_BK = PurchaselistBk.PURCHASELIST_BK;

    /**
     * The table <code>skillbox.students</code>.
     */
    public static final Students STUDENTS = Students.STUDENTS;

    /**
     * The table <code>skillbox.subscriptions</code>.
     */
    public static final Subscriptions SUBSCRIPTIONS = Subscriptions.SUBSCRIPTIONS;

    /**
     * The table <code>skillbox.teachers</code>.
     */
    public static final Teachers TEACHERS = Teachers.TEACHERS;
}
