/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.time.LocalDateTime;

import model.tables.Purchaselist;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaselistRecord extends TableRecordImpl<PurchaselistRecord> implements Record4<String, String, Integer, LocalDateTime> {

    private static final long serialVersionUID = -1914197186;

    /**
     * Setter for <code>skillbox.purchaselist.student_name</code>.
     */
    public void setStudentName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>skillbox.purchaselist.student_name</code>.
     */
    public String getStudentName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>skillbox.purchaselist.course_name</code>.
     */
    public void setCourseName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>skillbox.purchaselist.course_name</code>.
     */
    public String getCourseName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>skillbox.purchaselist.price</code>.
     */
    public void setPrice(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>skillbox.purchaselist.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>skillbox.purchaselist.subscription_date</code>.
     */
    public void setSubscriptionDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>skillbox.purchaselist.subscription_date</code>.
     */
    public LocalDateTime getSubscriptionDate() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, Integer, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, Integer, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Purchaselist.PURCHASELIST.STUDENT_NAME;
    }

    @Override
    public Field<String> field2() {
        return Purchaselist.PURCHASELIST.COURSE_NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Purchaselist.PURCHASELIST.PRICE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Purchaselist.PURCHASELIST.SUBSCRIPTION_DATE;
    }

    @Override
    public String component1() {
        return getStudentName();
    }

    @Override
    public String component2() {
        return getCourseName();
    }

    @Override
    public Integer component3() {
        return getPrice();
    }

    @Override
    public LocalDateTime component4() {
        return getSubscriptionDate();
    }

    @Override
    public String value1() {
        return getStudentName();
    }

    @Override
    public String value2() {
        return getCourseName();
    }

    @Override
    public Integer value3() {
        return getPrice();
    }

    @Override
    public LocalDateTime value4() {
        return getSubscriptionDate();
    }

    @Override
    public PurchaselistRecord value1(String value) {
        setStudentName(value);
        return this;
    }

    @Override
    public PurchaselistRecord value2(String value) {
        setCourseName(value);
        return this;
    }

    @Override
    public PurchaselistRecord value3(Integer value) {
        setPrice(value);
        return this;
    }

    @Override
    public PurchaselistRecord value4(LocalDateTime value) {
        setSubscriptionDate(value);
        return this;
    }

    @Override
    public PurchaselistRecord values(String value1, String value2, Integer value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurchaselistRecord
     */
    public PurchaselistRecord() {
        super(Purchaselist.PURCHASELIST);
    }

    /**
     * Create a detached, initialised PurchaselistRecord
     */
    public PurchaselistRecord(String studentName, String courseName, Integer price, LocalDateTime subscriptionDate) {
        super(Purchaselist.PURCHASELIST);

        set(0, studentName);
        set(1, courseName);
        set(2, price);
        set(3, subscriptionDate);
    }
}
