/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.time.LocalDateTime;

import model.tables.PurchaselistBk;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaselistBkRecord extends UpdatableRecordImpl<PurchaselistBkRecord> implements Record5<Integer, String, String, Integer, LocalDateTime> {

    private static final long serialVersionUID = -50900040;

    /**
     * Setter for <code>skillbox.purchaselist_bk.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>skillbox.purchaselist_bk.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>skillbox.purchaselist_bk.student_name</code>.
     */
    public void setStudentName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>skillbox.purchaselist_bk.student_name</code>.
     */
    public String getStudentName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>skillbox.purchaselist_bk.course_name</code>.
     */
    public void setCourseName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>skillbox.purchaselist_bk.course_name</code>.
     */
    public String getCourseName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>skillbox.purchaselist_bk.price</code>.
     */
    public void setPrice(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>skillbox.purchaselist_bk.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>skillbox.purchaselist_bk.subscription_date</code>.
     */
    public void setSubscriptionDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>skillbox.purchaselist_bk.subscription_date</code>.
     */
    public LocalDateTime getSubscriptionDate() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Integer, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, Integer, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PurchaselistBk.PURCHASELIST_BK.ID;
    }

    @Override
    public Field<String> field2() {
        return PurchaselistBk.PURCHASELIST_BK.STUDENT_NAME;
    }

    @Override
    public Field<String> field3() {
        return PurchaselistBk.PURCHASELIST_BK.COURSE_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return PurchaselistBk.PURCHASELIST_BK.PRICE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return PurchaselistBk.PURCHASELIST_BK.SUBSCRIPTION_DATE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getStudentName();
    }

    @Override
    public String component3() {
        return getCourseName();
    }

    @Override
    public Integer component4() {
        return getPrice();
    }

    @Override
    public LocalDateTime component5() {
        return getSubscriptionDate();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getStudentName();
    }

    @Override
    public String value3() {
        return getCourseName();
    }

    @Override
    public Integer value4() {
        return getPrice();
    }

    @Override
    public LocalDateTime value5() {
        return getSubscriptionDate();
    }

    @Override
    public PurchaselistBkRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PurchaselistBkRecord value2(String value) {
        setStudentName(value);
        return this;
    }

    @Override
    public PurchaselistBkRecord value3(String value) {
        setCourseName(value);
        return this;
    }

    @Override
    public PurchaselistBkRecord value4(Integer value) {
        setPrice(value);
        return this;
    }

    @Override
    public PurchaselistBkRecord value5(LocalDateTime value) {
        setSubscriptionDate(value);
        return this;
    }

    @Override
    public PurchaselistBkRecord values(Integer value1, String value2, String value3, Integer value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurchaselistBkRecord
     */
    public PurchaselistBkRecord() {
        super(PurchaselistBk.PURCHASELIST_BK);
    }

    /**
     * Create a detached, initialised PurchaselistBkRecord
     */
    public PurchaselistBkRecord(Integer id, String studentName, String courseName, Integer price, LocalDateTime subscriptionDate) {
        super(PurchaselistBk.PURCHASELIST_BK);

        set(0, id);
        set(1, studentName);
        set(2, courseName);
        set(3, price);
        set(4, subscriptionDate);
    }
}
