/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.time.LocalDateTime;

import model.tables.Subscriptions;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubscriptionsRecord extends TableRecordImpl<SubscriptionsRecord> implements Record3<UInteger, UInteger, LocalDateTime> {

    private static final long serialVersionUID = -1429527858;

    /**
     * Setter for <code>skillbox.subscriptions.student_id</code>.
     */
    public void setStudentId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>skillbox.subscriptions.student_id</code>.
     */
    public UInteger getStudentId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>skillbox.subscriptions.course_id</code>.
     */
    public void setCourseId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>skillbox.subscriptions.course_id</code>.
     */
    public UInteger getCourseId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>skillbox.subscriptions.subscription_date</code>.
     */
    public void setSubscriptionDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>skillbox.subscriptions.subscription_date</code>.
     */
    public LocalDateTime getSubscriptionDate() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UInteger, UInteger, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UInteger, UInteger, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Subscriptions.SUBSCRIPTIONS.STUDENT_ID;
    }

    @Override
    public Field<UInteger> field2() {
        return Subscriptions.SUBSCRIPTIONS.COURSE_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Subscriptions.SUBSCRIPTIONS.SUBSCRIPTION_DATE;
    }

    @Override
    public UInteger component1() {
        return getStudentId();
    }

    @Override
    public UInteger component2() {
        return getCourseId();
    }

    @Override
    public LocalDateTime component3() {
        return getSubscriptionDate();
    }

    @Override
    public UInteger value1() {
        return getStudentId();
    }

    @Override
    public UInteger value2() {
        return getCourseId();
    }

    @Override
    public LocalDateTime value3() {
        return getSubscriptionDate();
    }

    @Override
    public SubscriptionsRecord value1(UInteger value) {
        setStudentId(value);
        return this;
    }

    @Override
    public SubscriptionsRecord value2(UInteger value) {
        setCourseId(value);
        return this;
    }

    @Override
    public SubscriptionsRecord value3(LocalDateTime value) {
        setSubscriptionDate(value);
        return this;
    }

    @Override
    public SubscriptionsRecord values(UInteger value1, UInteger value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubscriptionsRecord
     */
    public SubscriptionsRecord() {
        super(Subscriptions.SUBSCRIPTIONS);
    }

    /**
     * Create a detached, initialised SubscriptionsRecord
     */
    public SubscriptionsRecord(UInteger studentId, UInteger courseId, LocalDateTime subscriptionDate) {
        super(Subscriptions.SUBSCRIPTIONS);

        set(0, studentId);
        set(1, courseId);
        set(2, subscriptionDate);
    }
}
